data_type: "real"
FPS: 30
substeps: 60
dt: 0.00055556
num_substeps: 60
spring_ke: 25000.0
spring_kd: 15.0
particle_radius: 0.0028
particle_mass: 1.0
k_neighbors: 30
controller_k: 10
spring_neighbor_mode: "radius"
object_radius: 0.03
object_radius_min: 0.01
object_radius_max: 0.05
object_max_neighbours: 32
scale: 1.0
z_offset: 0.02
use_controllers: true
controller_ke: 2500.0
controller_kd: 5.0
filter_visibility: false
filter_motion_valid: false
drag_damping: 0.1
base_lr: 1e-2
iterations: 100
log_params: true
grad_clip: 100.0
spring_ke_min: 10000.0
spring_ke_max: 50000.0
spring_kd_min: 10.3
spring_kd_max: 70.2
particle_radius_min: 0.001
particle_radius_max: 0.01
vis_interval: 20
collide_elas: 0.5
collide_elas_min: 0.3
collide_elas_max: 0.7
collide_fric: 0.3
collide_fric_min: 0.1
collide_fric_max: 0.5
collide_object_elas: 0.7
collide_object_elas_min: 0.5
collide_object_elas_max: 0.9
collide_object_fric: 0.3
collide_object_fric_min: 0.1
collide_object_fric_max: 0.5
reverse_z: true
vp_front: [1, 0, -2]
vp_up: [0, 0, -1]
vp_zoom: 1
collision_dist: 0.02
collision_learn: true
chamfer_weight: 1.0
track_weight: 1.0
acc_weight: 1.0
self_collision: true
compare_offset: 1.0
compare_symmetric: true
predict_controller_color: [0.2, 1.0, 0.2]
visualize_mesh: true
mesh_method: "pca_delaunay"
mesh_edge_factor: 4.0
mesh_show_points: false
mesh_show_gt: false
